### PR TITLE
[RFR] OPBEAT_CONFIG_FILE to select filepath in opbeat/start

### PR DESCRIPTION
**Pull request by Kmaschta**
Usage:
```js
import opbeat from 'opbeat/start';
```

```bash
OPBEAT_CONFIG_FILE="build/opbeat.js" node --require opbeat/start app.js
```

### CODE REVIEW

**Comment by Kmaschta** [comment]
Thanks Thomas @watson for the help, here is a PR to fullfill my needs!

**Comment by watson** [comment]
Awesome @Kmaschta 👍

Can I make one suggestion: I'd like to call this environment variable `OPBEAT_CONFIG_FILE` so it's not grammatically tied to the start script. Right now it only works with the start script, but in the future I was thinking to allow this for general configuration as well 😄

**Comment by Kmaschta** [comment]
Done!

**Comment by watson** [comment]
It's now published as v4.9.0 on npm - thanks for the help 😃

**Pull request merged**
